platform:ios, ‘9.0’

inhibit_all_warnings!

use_frameworks!		

target ‘OCDemo01’ do

pod 'AFNetworking'
pod 'Masonry'
pod 'SDWebImage'
pod 'TPKeyboardAvoiding'
pod 'MJRefresh'
pod 'YYCategories'
pod 'SCLAlertView-Objective-C'

end